version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

  client-redis:
    image: redis/redis-stack-server:latest
    container_name: redis_client
    ports:
      - '6379:6379'

networks:
  default:
    driver: bridge
